#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

pipenv run python manage.py migrate
pipenv run python manage.py create_refresh_countries_cron
pipenv run python manage.py runserver 0.0.0.0:8000
